### ISSUE TITLE
c-clips faill as "blob unavailable" but are readable with JCASScript.jar

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ecs-sync#111]
Hello,
at a customer site I have more than 7000 c-clips failing copy from Centera to ECS with a 'blob unavailable' error message, but when I use the ClipToFile command of JCASScript.jar the ClipToFile command works successfully.

Here is the stack trace:

2024-07-05 08:10:17 WARN  [sync-pool-4-t-32] SyncTask: O--! object 3A08XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAJTPLL failed
java.lang.RuntimeException: [3A08XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAJTPLL.0]: blob unavailable (status=0)
        at com.emc.ecs.sync.storage.cas.EnhancedTag.<init>(EnhancedTag.java:56) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.storage.cas.ClipSyncObject.loadNextTag(ClipSyncObject.java:101) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.storage.cas.ClipSyncObject.access$100(ClipSyncObject.java:33) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.storage.cas.ClipSyncObject$1$1.getNextObject(ClipSyncObject.java:142) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.storage.cas.ClipSyncObject$1$1.getNextObject(ClipSyncObject.java:135) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.util.ReadOnlyIterator.hasNext(ReadOnlyIterator.java:32) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.storage.cas.CasStorage.loadObject(CasStorage.java:336) ~[ecs-sync-3.5.3.jar:3.5.3]
        at com.emc.ecs.sync.SyncTask.run(SyncTask.java:75) [ecs-sync-3.5.3.jar:3.5.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

Looking at code show that this error is raised when the tag.BlobExists() method return false, but when I navigate inside the c-clip using JCASScript it says blobexists is true.

Here is the c-clip eclipcontents structure:

\<eclipcontents\>
<STORAGE_CENTER>
\<eclipblob md5="3SEXXXXXXXXXXXXXXXXXXXXX7U3" size="991863" offset="0"\/\>
\</STORAGE_CENTER\>
\</eclipcontents\>

What should be the conditions where the ECSSync function returns something different as JCASScript ?

Thanks for your help.

**Comment by dunedodo** [comment]
Thanks for reaching us. Please send us your detailed request/issue by ECS Sync Support <ecs.sync.support@dell.com> if you still have problem on it.

**Comment by dunedodo** [comment]
Thanks @lriva94 I will close this issue.
