### ISSUE TITLE
 There was a mismatch between the signature in the request and the signature computed by the server

### ISSUE THREAD

**Issue by lriva94** [EMCECS/ecs-sync#38]
Hello,
I ran several ATMOS REST migrations (from ATMOS 2.4.2 to ECS 3.2.0.1) without any problem, but with one particular job I have the following error with ecs-sync 3.2.9:

AtmosException{errorCode=1032, httpCode=403} com.emc.atmos.AtmosException: There was a mismatch between the signature in the request and the signature computed by the server.
        at com.emc.atmos.api.jersey.ErrorFilter.handle(ErrorFilter.java:75)
        at com.emc.atmos.api.jersey.RetryFilter.handle(RetryFilter.java:63)
        at com.emc.atmos.api.jersey.AuthFilter.handle(AuthFilter.java:53)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.get(WebResource.java:193)
        at com.emc.atmos.api.jersey.AtmosApiClient.getServiceInformation(AtmosApiClient.java:157)
        at com.emc.ecs.sync.storage.AtmosStorage.configure(AtmosStorage.java:165)
        at com.emc.ecs.sync.EcsSync.run(EcsSync.java:212)
        at com.emc.ecs.sync.service.SyncJobService$SyncTask.run(SyncJobService.java:339)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I can provide in private msg the XML file of the job migration.
What could be the different reasons that could raise this error ?

Thank you

**Comment by lriva94** [comment]
The error was due to a wrong secret on the ATMOS part of the XML config file.
