### ISSUE TITLE
UI crashed if job name contains space

### ISSUE THREAD

**Issue by shvc** [EMCECS/ecs-sync#53]
#### 3. UI crashed
- ecs-sync-ui.log
```
2019-05-15 11:29:26.405 ERROR --- [0.1-8080-exec-4] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/history/index.gsp:51] Error executing tag <sitemesh:captureBody>: Illegal character in path at index 44: /download/archive/report/20190515T112813-job name.report.csv] with root cause

java.net.URISyntaxException: Illegal character in path at index 44: /download/archive/report/20190515T112813-job name.report.csv
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3063)
        at java.net.URI.<init>(URI.java:588)
```
- archive file name contains a space
`/opt/emc/ecs-sync/config/archive/20190515T112813-job name.xml`

**Comment by twincitiesguy** [comment]
Fixed in 3.3.1
