### ISSUE TITLE
com.emc.object.s3.S3Exception: Object Moved

### ISSUE THREAD

**Issue by geoffwi** [EMCECS/ecs-sync#65]
When trying to start a new write to an already created, empty bucket, I get:
General Error: [com.emc.object.s3.S3Exception: Object Moved] com.emc.object.s3.S3Exception: Object Moved
    at com.emc.object.s3.jersey.ErrorFilter.handle(ErrorFilter.java:80)
    at com.emc.object.s3.jersey.RetryFilter.handle(RetryFilter.java:65)
    at com.emc.object.s3.jersey.ChecksumFilter.handle(ChecksumFilter.java:73)
    at com.emc.object.s3.jersey.AuthorizationFilter.handle(AuthorizationFilter.java:72)
    at com.emc.object.s3.jersey.BucketFilter.handle(BucketFilter.java:80)
    at com.emc.object.s3.jersey.NamespaceFilter.handle(NamespaceFilter.java:78)
    at com.sun.jersey.api.client.Client.handle(Client.java:652)
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.method(WebResource.java:623)
    at com.emc.object.AbstractJerseyClient.executeRequest(AbstractJerseyClient.java:107)
    at com.emc.object.AbstractJerseyClient.executeAndClose(AbstractJerseyClient.java:54)
    at com.emc.object.s3.jersey.S3JerseyClient.bucketExists(S3JerseyClient.java:290)
    at com.emc.ecs.sync.storage.s3.EcsS3Storage.configure(EcsS3Storage.java:129)
    at com.emc.ecs.sync.EcsSync.run(EcsSync.java:214)

**Comment by twincitiesguy** [comment]
It's hard to say for sure, as there is not a lot of info above, but I would guess that you are using the wrong port when configuring the ECS S3 plugin.  If you are going directly to the nodes, you should keep the smart client enabled, and leave the port blank (or -1).  If you are hitting a load balancer in front of the ECS, be sure to specify the correct port for S3 on the load balancer (even if it is default - 80 or 443) and disable the smart-client.

**Comment by twincitiesguy** [comment]
closing due to inactivity
