### ISSUE TITLE
Could not create task of type 'ShadowJar’.

### ISSUE THREAD

**Issue by GrandPubba** [EMCECS/ecs-sync#7]
When building the project I get:

```
* What went wrong:
A problem occurred evaluating root project 'ecs-sync'.
> Failed to apply plugin [class 'com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin']
   > Could not create task of type 'ShadowJar’.
```

When I printed the stack trace I found:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.java.archives.internal.DefaultManifest.<init>(Lorg/gradle/api/internal/file/FileResolver;)V
at com.github.jengelman.gradle.plugins.shadow.tasks.DefaultInheritManifest.<init>(DefaultInheritManifest.groovy:15)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.<init>(ShadowJar.java:44)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar_Decorated.<init>(Unknown Source)
at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
... 89 more
```

This is likely as a result of the following issue https://github.com/johnrengelman/shadow/issues/177.  Upgrading seems to resolve the issue.  PR to follow shortly.

**Comment by twincitiesguy** [comment]
Incorporated fix into development repository; will be pushed to github with next release
