### ISSUE TITLE
Main process interrupt caused by An invalid XML character (Unicode: 0x7) was found in the element content of the document V3.4.0

### ISSUE THREAD

**Issue by truezjz** [EMCECS/ecs-sync#78]
2021-03-19 19:25:05 ERROR [main           ] EcsSync: unexpected exception
javax.ws.rs.WebApplicationException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An invalid X
ML character (Unicode: 0x7) was found in the element content of the document.]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.readFro
m(AbstractRootElementProvider.java:113)
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.jav
a:634)
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.jav
a:586)
        at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient
.java:735)
        at com.emc.object.s3.jersey.S3JerseyClient.listObjects(S3JerseyClient.ja
va:489)
        at com.emc.object.s3.jersey.S3JerseyClient.listMoreObjects(S3JerseyClien
t.java:497)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.lambda$getNex
tBatch$1(EcsS3Storage.java:767)
        at com.emc.ecs.sync.util.TimingUtil.time(TimingUtil.java:55)
        at com.emc.ecs.sync.AbstractPlugin.time(AbstractPlugin.java:72)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage.access$200(EcsS3Storage.java
:52)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextBatch(
EcsS3Storage.java:767)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextObject
(EcsS3Storage.java:744)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextObject
(EcsS3Storage.java:732)
        at com.emc.ecs.sync.util.ReadOnlyIterator.hasNext(ReadOnlyIterator.java:
31)
        at com.emc.ecs.sync.EcsSync.run(EcsSync.java:333)
        at com.emc.ecs.sync.EcsSync.main(EcsSync.java:108)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An invalid X
ML character (Unicode: 0x7) was found in the element content of the document.]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalExcept
ion(AbstractUnmarshallerImpl.java:335)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmar
shalException(UnmarshallerImpl.java:523)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(
UnmarshallerImpl.java:220)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(U
nmarshallerImpl.java:189)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:140)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:123)
        at com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider.readF
rom(XMLRootElementProvider.java:115)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.readFro
m(AbstractRootElementProvider.java:111)
        ... 15 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An
 invalid XML character (Unicode: 0x7) was found in the element content of the do
cument.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAX
ParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalErro
r(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(
XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(
XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(X
MLScanner.java:1473)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2923)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next
(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:643)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(
UnmarshallerImpl.java:216)
        ... 20 more
javax.ws.rs.WebApplicationException: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An invalid X
ML character (Unicode: 0x7) was found in the element content of the document.]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.readFro
m(AbstractRootElementProvider.java:113)
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.jav
a:634)
        at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.jav
a:586)
        at com.emc.object.s3.jersey.S3JerseyClient.executeRequest(S3JerseyClient
.java:735)
        at com.emc.object.s3.jersey.S3JerseyClient.listObjects(S3JerseyClient.ja
va:489)
        at com.emc.object.s3.jersey.S3JerseyClient.listMoreObjects(S3JerseyClien
t.java:497)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.lambda$getNex
tBatch$1(EcsS3Storage.java:767)
        at com.emc.ecs.sync.util.TimingUtil.time(TimingUtil.java:55)
        at com.emc.ecs.sync.AbstractPlugin.time(AbstractPlugin.java:72)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage.access$200(EcsS3Storage.java
:52)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextBatch(
EcsS3Storage.java:767)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextObject
(EcsS3Storage.java:744)
        at com.emc.ecs.sync.storage.s3.EcsS3Storage$PrefixIterator.getNextObject
(EcsS3Storage.java:732)
        at com.emc.ecs.sync.util.ReadOnlyIterator.hasNext(ReadOnlyIterator.java:
31)
        at com.emc.ecs.sync.EcsSync.run(EcsSync.java:333)
        at com.emc.ecs.sync.EcsSync.main(EcsSync.java:108)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An invalid X
ML character (Unicode: 0x7) was found in the element content of the document.]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalExcept
ion(AbstractUnmarshallerImpl.java:335)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmar
shalException(UnmarshallerImpl.java:523)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(
UnmarshallerImpl.java:220)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(U
nmarshallerImpl.java:189)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:140)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:123)
        at com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider.readF
rom(XMLRootElementProvider.java:115)
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.readFro
m(AbstractRootElementProvider.java:111)
        ... 15 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 40515; An
 invalid XML character (Unicode: 0x7) was found in the element content of the do
cument.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAX
ParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalErro
r(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(
XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(
XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(X
MLScanner.java:1473)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2923)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(X
MLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next
(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImp
l.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Ab
stractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.p
arse(SAXParserImpl.java:643)
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(
UnmarshallerImpl.java:216)
        ... 20 more

**Comment by Gabby-ScaleIO** [comment]
unsubscribe
