### ISSUE TITLE
Deleting a CAS bucket with ecs-sync and got this error

### ISSUE THREAD

**Issue by ergonzalezn** [EMCECS/ecs-sync#80]
HI 

not sure if the community can help, I got the fllowing error message, that completely errored out the deletion Job I have been doing on a CAS bucket

java.lang.RuntimeException: received FP_QUERY_RESULT_CODE_ABORT error, exiting.] java.lang.RuntimeException: received FP_QUERY_RESULT_CODE_ABORT error, exiting. at com.emc.ecs.sync.storage.cas.CasStorage$2$1.getNextObject(CasStorage.java:261) at com.emc.ecs.sync.storage.cas.CasStorage$2$1.getNextObject(CasStorage.java:210) at com.emc.ecs.sync.util.ReadOnlyIterator.hasNext(ReadOnlyIterator.java:31) at com.emc.ecs.sync.EcsSync.run(EcsSync.java:333) at com.emc.ecs.sync.service.SyncJobService$SyncTask.run(SyncJobService.java:333) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by xiaoxin-ren** [comment]
FP_QUERY_RESULT_CODE_ABORT error is raised in listing objects, indicating that the query is aborted due to server side issue or start time is later than server time. That's clue for you to check. Would recommend opening a service ticket so that customer support could get involved and help.

**Comment by ergonzalezn** [comment]
thanks xiaoXin, so is this a problem with ECS?

**Comment by xiaoxin-ren** [comment]
It's a CAS error returned by the CAS server. Have you checked the system time of CAS server and server running ecs-sync? If you hit error in syncing CAS into ECS CAS bucket by ecs-sync, no problem to involve ECS customer support first.

**Comment by ergonzalezn** [comment]
Seems that disabling it help. but it seems that the jobs entered a roadblock where even starting new jobs fails at 700 objects. turns out the error messages are:

CAS Error -10204/FP_OPERATION_NOT_ALLOWED: The use of this operation is restricted (transid='ECSOVAHOST/148819284/DELETE_CLIP')

we even enabled the privileged delete option and still not getting why its failing.

can you help?

**Comment by xiaoxin-ren** [comment]
I would recommend you to create a service ticket for this because no direct clue showing an issue in ecs-sync, it's more like a configuration or privilege issue. Additional troubleshooting in ecs-sync could be temporarily turning up debug level and checking  what's in /var/log/ecs-sync/ecs-sync.log. Also you can isolate the issue by checking whether the operation succeeds without using ecs-sync.

**Comment by twincitiesguy** [comment]
closing due to inactivity
